fix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,17 +26,19 @@ runs:
   using: composite
   steps:
     - uses: shorebirdtech/setup-shorebird@v0
-      id: shorebird-release
       with:
         flutter-version: ${{ inputs.flutter-version }}
+
+    - name: Shorebird Release
+      shell: bash
+      working-directory: ${{ inputs.working-directory }}
       run: |
         OUTPUT=$(shorebird release ${{ inputs.platform }})
         REGEXP="Published Release (.*)!"
         if [[ $OUTPUT =~ $REGEXP ]]; then
-            RELEASE_VERSION=${BASH_REMATCH[1]}
-            echo "release-version=$(echo $RELEASE_VERSION)" >> $GITHUB_OUTPUT
+        RELEASE_VERSION=${BASH_REMATCH[1]}
+        echo "release-version=$(echo $RELEASE_VERSION)" >> $GITHUB_OUTPUT
         else
-            echo "Failed to create release"
-            exit 1    
+        echo "Failed to create release"
+        exit 1
         fi
-      working-directory: ${{ inputs.working-directory }}
